config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/home' => 'static_pages#home'

  get '/aboutme' => 'static_pages#aboutme'

  get '/portfolio' => 'static_pages#portfolio'

  get '/gallery' => 'static_pages#gallery'

  get '/contact' => 'static_pages#contact'

  get '/mathgame' => 'static_pages#mathgame'

  get '/travel' => 'static_pages#travel'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    # we dont have any logics here
    # so we are just going to render the page 'index.html'
  end

  def home
    
  end

  def aboutme
    
  end

  def portfolio
    
  end
  
  def gallery
    
  end

  def contact
    
  end

  def mathgame

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container-fluid footer">
  <div class="row">
    <span class="footline">
      <ul class="social col-sm-6">
        <li class="icon"><a href="https://github.com/cassiemak/" class="iconicon"><i class="fa fa-github-square fa-2x"></i></a></li>
        <li class="icon"><a href="http://linkedin.com/in/cassiemak" class="iconicon"><i class="fa fa-linkedin-square fa-2x"></i></a></li>
        <li class="icon"><a href="http://facebook.com/cassiemak" class="iconicon"><i class="fa fa-facebook-square fa-2x"></i></a></li>
        <li class="icon"><a href="http://instagram.com/sassycassandra" class="iconicon"><i class="fa fa-instagram fa-2x"></i></a></li>
        <li class="icon"><a href="https://plus.google.com/+CassandraMak/" class="iconicon"><i class="fa fa-google-plus-square fa-2x"></i></a></li>
        <li class="icon"><a href="http://www.pinterest.com/cassandramak/" class="iconicon"><i class="fa fa-pinterest-square fa-2x"></i></a></li>
        <li class="icon"><a href="https://dl.dropboxusercontent.com/u/7814617/cassie-skypeqrcode.png" class="iconicon"><i class="fa fa-weixin fa-2x"></i></a></li>
        <li class="icon"><a href="" class="iconicon"><i class="fa fa-skype fa-2x"></i></a></li>
      </ul>
    </span>
    <span class="footline">
    <ul class="contactinfo col-sm-6">
      <li class="info"><i class="fa fa-envelope fa-2x"></i><div class="phone"> cassie[dot]mak[at]gmail[dot]com
      <% #mail_to "cassie.mak@gmail.com", "Email ", :class => "emailaddress" %>
      </div></li>
    <li class="info"><i class="fa fa-phone-square fa-2x"></i><div class="phone"> (852) </div></li>
    </ul>
    </span>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 ">
      <div class="col-xs-11 col-sm-4">
        <h1 id="myName">CASSIE MAK</h1>
      </div>

      <div class="col-xs-1 col-sm-8 nav navbar" id="menu">
        <ul class="topMenu">
          <li class="list"><%= link_to "HOME", home_path, :class => "menuList" %></li>
          <li class="list"><%= link_to "ABOUT", aboutme_path, :class => "menuList" %></li>
          <li class="list"><%= link_to "PORTFOLIO", portfolio_path, :class => "menuList" %></li>
          <li class="list"><%= link_to "GALLERY", gallery_path, :class => "menuList" %></li>
          <li class="list"><%= link_to "TRAVEL", travel_path, :class => "menuList" %></li>
          <li class="list"><%= link_to "CONTACT", contact_path, :class => "menuList"%></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="cassie">
  <head>
    <title>Cassie Mak</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'logo.jpg' %>
    <link href='https://fonts.googleapis.com/css?family=Alex+Brush|Frijole|Rock+Salt|Sancreek' rel='stylesheet' type='text/css'>
    <meta name="p:domain_verify" content="39f0e831a7f8aa04277ea2c3d927eb9f"/>
    <script src='//maps.googleapis.com/maps/api/js?libraries=geometry&amp;sensor=false'></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-61141025-1', 'auto');
      ga('send', 'pageview');
    </script>
    <%= csrf_meta_tags %>

  </head>

  <body ng-view>
    <h1>Cassie Mak =)</h1>
  </body>
</html>

app/views/static_pages/aboutme.html.erb
<div class="container-fluid cassie"> 
  <%= render 'layouts/header' %>
  <div class="row vertical-center">
    <div class="col-xs-8 col-xs-offset-2" id="aboutSquare">
      <p>Born in Toronto, Canada, I spent most of my childrenhood in Hong Kong. 
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et cupidatat nonproident, sunt in culpa qui officia 
      deserunt mollit anim id estaborum.</p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>

app/views/static_pages/cassie.html.erb
<div class="container-fluid cassie"> 
  <%= render 'layouts/header' %>
  <div class="row vertical-center">
  <div>Cassie Page</div>

</div>

app/views/static_pages/contact.html.erb
<div id="map-canvas"> 
</div>
<div class="container-fluid contact"> 
  <%= render 'layouts/header' %>
  <div class="row vertical-center">
    <div class="col-sm-8 col-sm-offset-2">
      <!-- Call me maybe -->
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <%= form_for :person do |f| %>
            <table>
              <tr><h3>Leave me a message!</h3></tr>
              <tr>
                <td><h5>Name: </h5></td><td><%= f.text_field :name%><br/></td>
              </tr>
              <tr>
                <td><h5>Email Address: </h5></td><td><%= f.text_field :email %><br/></td>
              </tr>
              <tr>
                <td><h5>Message: </h5></td><td><%= f.text_area :message, :id => 'contact-message-box' %><br/></td>
              </tr>
              <tr>
                <td><%= f.submit :class => "btn btn-sm btn-primary", :value => 'SUBMIT' %></td>
              </tr>
            </table>
          <% end %>
        </div>
      </div>
      <div id="myHome">
        
      </div>
      <div id="mySchool">
        
      </div>
      <div id="myBirthPlace">
        
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>

app/views/static_pages/gallery.html.erb
<div class="container-fluid gallery">
  <%= render 'layouts/header' %> 
  <div class="row vertical-center">
    <div class="col-sm-8 col-sm-offset-2 text-center picture-grid">
      <!-- Carousel/ Grid of pictures -->
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators / the dots below the carousel  -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <!-- <li data-target="#carousel-example-generic" data-slide-to="2"></li> -->
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

          <div class="item active">
            <%= image_tag "BlackSandBeach.JPG", :class => "gallery-pix" %>
            <!-- <img src="assets/BlackSandBeach.JPG" alt="..." style="border-radius: 15px"> -->
            <div class="carousel-caption">
              Iceland - Black Sand Beach with Ice
            </div>
          </div>
          <div class="item">
            <%= image_tag "CassieIceBeach.JPG", :class => "gallery-pix" %>
            <!-- <img src="assets/CassieIceBeach.JPG" alt="..." style="border-radius: 15px"> -->
            <div class="carousel-caption">
              Wow - Big Ice
            </div>
          </div>
          <h2>Trotting Around The World</h2>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>


    </div>
  </div>
  <%= render 'layouts/footer' %>
</div> 
  
<!--   
  <div class="masthead segment">
    <div class="ui page grid">
      <div class="column">
        <div class="introduction">
          <h1 class="ui inverted header">
            <span class="text">Gallery</span>
          </h1>
          <div class="ui hidden divider"></div>
        </div>
      </div>
    </div>
  </div> 
  -->

app/views/static_pages/home.html.erb
<div class="container-fluid home">
  <%= render 'layouts/header' %>
  <div class="row vertical-center">
    <div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-6 vertical-center" id="mytitle">
      <h2 class="title_des">Web Developer</h2>
      <h2 class="title_des">Entrepreneur</h2>
      <h2 class="title_des">Digital Marketer</h2>
      <h2 class="title_des">Jet Setter</h2>
      <h2 class="title_des">Event Planner</h2>
      <h2 class="title_des">Dodgeball Player</h2>
      <h2 class="title_des">Seaonal Performer</h2>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>

app/views/static_pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <h1>HIHI</h1>
      <%= #link_to "Link to Cassie Path", cassie_path %>
      <%= #link_to "Link to Mathgame", mathgame_path %> 
      <%= #link_to "Facebook", 'http://facebook.com' %>
    </div>
  </div>
</div>

app/views/static_pages/portfolio.html.erb
<div class="container-fluid portfolio"> 
  <%= render 'layouts/header' %>
  <div class="row vertical-center">
    <div class="col-sm-8 col-sm-offset-2 text-center">

      <div class="minuspadding col-sm-3">
        <div class="outer mamahen">
          <div class="inner project">
            <p class="project-name">Startup -</br> mamahen.com.hk,</br> the ultimate gift registry</p>
            <a href="http://www.mamahen.com.hk/"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

      <div class="minuspadding col-sm-3">
        <div class="outer shoppingcart">
          <div class="inner project">
            <p class="project-name">Javascript -</br> Simple Shopping Cart</p>
            <a href="http://sassy-simple-shopping-cart.bitballoon.com"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

      <div class="minuspadding col-sm-3">
        <div class="outer mathgame">
          <div class="inner project">
            <p class="project-name">Javascript -</br> 10 Seconds of Math</p>
            <a href="http://sassy-math.bitballoon.com"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

      <div class="minuspadding col-sm-3">
        <div class="outer reddit">
          <div class="inner project">
            <p class="project-name">Javascript -</br>Reddit</p>
            <a href="https://sassy-reddit.herokuapp.com/"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

      <div class="minuspadding col-sm-3">
        <div class="outer highchart">
          <div class="inner project">
            <p class="project-name">Javascript -</br> Highchart Annotation</p>
            <a href="http://highchart-annotation.bitballoon.com/"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

      <div class="minuspadding col-sm-3">
        <div class="outer siubobo">
          <div class="inner project">
            <p class="project-name">Ruby on Rails -</br> Baby Product Review</p>
            <a href="https://product-review.herokuapp.com/"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

      <div class="minuspadding col-sm-3">
        <div class="outer mamahen">
          <div class="inner project">
            <p class="project-name">Project 2 -</br> Project 2</p>
            <a href="#"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

      <div class="minuspadding col-sm-3">
        <div class="outer mamahen">
          <div class="inner project">
            <p class="project-name">Project 3 -</br> Project 3</p>
            <a href="#"><span class="emptyspan"></span></a>
          </div>
        </div>
      </div>

    </div>
  </div>
  <%= render 'layouts/footer' %> 
</div> 

app/views/static_pages/travel.html.erb
<div class="container-fluid travel">
  <%= render 'layouts/header' %>
  <div class="row vertical-center">
    <div class="col-sm-8 col-sm-offset-2 text-center">
      
      <p style="text-align: center">
        <!-- <a href="http://matadornetwork.com/travel-map/bafcbe09f7c997fe1c8ce5e80ede3b81-1417534472" title="Cassie’s Travel Map"> -->
        <!-- <img src="http://cdn1.matadornetwork.com/travel-maps/bafcbe09f7c997fe1c8ce5e80ede3b81-1417534472/my-travel-map.png" style="width: 100%; max-width: 100%" alt="Cassie’s Travel Map" /> -->
        <!-- </a> -->
      </p>
<!--       <p>Cassie has been to: 
        <a href="/destinations/oceania/australia/">Australia</a>, 
        <a href="/destinations/europe/austria/">Austria</a>, 
        <a href="/destinations/caribbean/bahamas/">Bahamas</a>, 
        <a href="/destinations/europe/belgium/">Belgium</a>, 
        <a href="/destinations/asia/cambodia/">Cambodia</a>, 
        <a href="/destinations/north-america/canada/">Canada</a>, 
        <a href="/destinations/asia/china/">China</a>, 
        <a href="/destinations/europe/croatia/">Croatia</a>, 
        <a href="/destinations/europe/czech-republic/">Czech Republic</a>, 
        <a href="/destinations/africa/egypt/">Egypt</a>, 
        <a href="/destinations/europe/estonia/">Estonia</a>, 
        <a href="/destinations/europe/finland/">Finland</a>, 
        <a href="/destinations/europe/france/">France</a>, 
        <a href="/destinations/europe/germany/">Germany</a>, 
        <a href="/destinations/europe/gibraltar/">Gibraltar</a>, 
        <a href="/destinations/europe/greece/">Greece</a>, 
        <a href="/destinations/oceania/guam/">Guam</a>, 
        <a href="/destinations/asia/hong-kong/">Hong Kong</a>, 
        <a href="/destinations/europe/hungary/">Hungary</a>, 
        <a href="/destinations/europe/iceland/">Iceland</a>, 
        <a href="/destinations/asia/indonesia/">Indonesia</a>, 
        <a href="/destinations/middle-east/israel/">Israel</a>, 
        <a href="/destinations/europe/italy/">Italy</a>, 
        <a href="/destinations/asia/japan/">Japan</a>, 
        <a href="/destinations/asia/macao/">Macao</a>, 
        <a href="/destinations/asia/malaysia/">Malaysia</a>, 
        <a href="/destinations/africa/morocco/">Morocco</a>, 
        <a href="/destinations/europe/netherlands/">Netherlands</a>, 
        <a href="/destinations/asia/philippines/">Philippines</a>, 
        <a href="/destinations/europe/portugal/">Portugal</a>, 
        <a href="/destinations/europe/russia/">Russia</a>, 
        <a href="/destinations/asia/singapore/">Singapore</a>, 
        <a href="/destinations/asia/south-korea/">South Korea</a>, 
        <a href="/destinations/europe/spain/">Spain</a>, 
        <a href="/destinations/europe/switzerland/">Switzerland</a>, 
        <a href="/destinations/asia/taiwan/">Taiwan</a>, 
        <a href="/destinations/asia/thailand/">Thailand</a>, 
        <a href="/destinations/asia/tibet/">Tibet</a>, 
        <a href="/destinations/asia/turkey/">Turkey</a>, 
        <a href="/destinations/europe/united-kingdom/">United Kingdom</a>, 
        <a href="/destinations/north-america/united-states/">United States</a>, 
        <a href="/destinations/asia/vietnam/">Vietnam</a>
      </p> -->

    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>